Male:   

  # BEHIND BODY TORSO (HEAD LEGS BELT FEET HANDS) WEAPON
  
  bow:
    [["JS_Male/png/bow/BODY_male.png"], ["JS_Male/png/bow/TORSO_chain_armor_jacket_purple.png", "JS_Male/png/bow/TORSO_chain_armor_torso.png", "JS_Male/png/bow/TORSO_leather_armor_bracers.png", "JS_Male/png/bow/TORSO_leather_armor_shirt_white.png", "JS_Male/png/bow/TORSO_leather_armor_shoulders.png", "JS_Male/png/bow/TORSO_leather_armor_torso.png", "JS_Male/png/bow/TORSO_plate_armor_arms_shoulders.png", "JS_Male/png/bow/TORSO_plate_armor_torso.png", "JS_Male/png/bow/TORSO_robe_shirt_brown.png"], ["JS_Male/png/bow/HEAD_chain_armor_helmet.png", "JS_Male/png/bow/HEAD_chain_armor_hood.png", "JS_Male/png/bow/HEAD_hair_blonde.png", "JS_Male/png/bow/HEAD_leather_armor_hat.png", "JS_Male/png/bow/HEAD_plate_armor_helmet.png", "JS_Male/png/bow/HEAD_robe_hood.png"], ["JS_Male/png/bow/LEGS_pants_greenish.png", "JS_Male/png/bow/LEGS_plate_armor_pants.png", "JS_Male/png/bow/LEGS_robe_skirt.png"], ["JS_Male/png/bow/BELT_leather.png", "JS_Male/png/bow/BELT_rope.png"], ["JS_Male/png/bow/FEET_plate_armor_shoes.png", "JS_Male/png/bow/FEET_shoes_brown.png"], ["JS_Male/png/bow/HANDS_plate_armor_gloves.png"], ["JS_Male/png/bow/WEAPON_arrow.png", "JS_Male/png/bow/WEAPON_bow.png"]]

  hurt:
    [["JS_Male/png/hurt/BEHIND_quiver.png"], ["JS_Male/png/hurt/BODY_male.png", "JS_Male/png/hurt/BODY_skeleton.png"], ["JS_Male/png/hurt/TORSO_chain_armor_jacket_purple.png", "JS_Male/png/hurt/TORSO_chain_armor_torso.png", "JS_Male/png/hurt/TORSO_leather_armor_bracers.png", "JS_Male/png/hurt/TORSO_leather_armor_shirt_white.png", "JS_Male/png/hurt/TORSO_leather_armor_shoulders.png", "JS_Male/png/hurt/TORSO_leather_armor_torso.png", "JS_Male/png/hurt/TORSO_plate_armor_arms_shoulders.png", "JS_Male/png/hurt/TORSO_plate_armor_torso.png", "JS_Male/png/hurt/TORSO_robe_shirt_brown.png"], ["JS_Male/png/hurt/BELT_leather.png", "JS_Male/png/hurt/BELT_rope.png"], ["JS_Male/png/hurt/FEET_plate_armor_shoes.png", "JS_Male/png/hurt/FEET_shoes_brown.png"], ["JS_Male/png/hurt/HANDS_plate_armor_gloves.png"], ["JS_Male/png/hurt/HEAD_chain_armor_helmet.png", "JS_Male/png/hurt/HEAD_chain_armor_hood.png", "JS_Male/png/hurt/HEAD_hair_blonde.png", "JS_Male/png/hurt/HEAD_leather_armor_hat.png", "JS_Male/png/hurt/HEAD_plate_armor_helmet.png", "JS_Male/png/hurt/HEAD_robe_hood.png"], ["JS_Male/png/hurt/LEGS_pants_greenish.png", "JS_Male/png/hurt/LEGS_plate_armor_pants.png", "JS_Male/png/hurt/LEGS_robe_skirt.png"]] 


  #copy of hurt except for this line

  fallen:
    [["JS_Male/png/hurt/BEHIND_quiver.png"], ["JS_Male/png/hurt/BODY_male.png", "JS_Male/png/hurt/BODY_skeleton.png"], ["JS_Male/png/hurt/TORSO_chain_armor_jacket_purple.png", "JS_Male/png/hurt/TORSO_chain_armor_torso.png", "JS_Male/png/hurt/TORSO_leather_armor_bracers.png", "JS_Male/png/hurt/TORSO_leather_armor_shirt_white.png", "JS_Male/png/hurt/TORSO_leather_armor_shoulders.png", "JS_Male/png/hurt/TORSO_leather_armor_torso.png", "JS_Male/png/hurt/TORSO_plate_armor_arms_shoulders.png", "JS_Male/png/hurt/TORSO_plate_armor_torso.png", "JS_Male/png/hurt/TORSO_robe_shirt_brown.png"], ["JS_Male/png/hurt/BELT_leather.png", "JS_Male/png/hurt/BELT_rope.png"], ["JS_Male/png/hurt/FEET_plate_armor_shoes.png", "JS_Male/png/hurt/FEET_shoes_brown.png"], ["JS_Male/png/hurt/HANDS_plate_armor_gloves.png"], ["JS_Male/png/hurt/HEAD_chain_armor_helmet.png", "JS_Male/png/hurt/HEAD_chain_armor_hood.png", "JS_Male/png/hurt/HEAD_hair_blonde.png", "JS_Male/png/hurt/HEAD_leather_armor_hat.png", "JS_Male/png/hurt/HEAD_plate_armor_helmet.png", "JS_Male/png/hurt/HEAD_robe_hood.png"], ["JS_Male/png/hurt/LEGS_pants_greenish.png", "JS_Male/png/hurt/LEGS_plate_armor_pants.png", "JS_Male/png/hurt/LEGS_robe_skirt.png"]] 

  slash:
    [["JS_Male/png/slash/BEHIND_quiver.png"], ["JS_Male/png/slash/BODY_male.png", "JS_Male/png/slash/BODY_skeleton.png"], ["JS_Male/png/slash/TORSO_chain_armor_jacket_purple.png", "JS_Male/png/slash/TORSO_chain_armor_torso.png", "JS_Male/png/slash/TORSO_leather_armor_bracers.png", "JS_Male/png/slash/TORSO_leather_armor_shirt_white.png", "JS_Male/png/slash/TORSO_leather_armor_shoulders.png", "JS_Male/png/slash/TORSO_leather_armor_torso.png", "JS_Male/png/slash/TORSO_plate_armor_arms_shoulders.png", "JS_Male/png/slash/TORSO_plate_armor_torso.png", "JS_Male/png/slash/TORSO_robe_shirt_brown.png"], ["JS_Male/png/slash/BELT_leather.png", "JS_Male/png/slash/BELT_rope.png"], ["JS_Male/png/slash/FEET_plate_armor_shoes.png", "JS_Male/png/slash/FEET_shoes_brown.png"], ["JS_Male/png/slash/HANDS_plate_armor_gloves.png"], ["JS_Male/png/slash/HEAD_chain_armor_helmet.png", "JS_Male/png/slash/HEAD_chain_armor_hood.png", "JS_Male/png/slash/HEAD_hair_blonde.png", "JS_Male/png/slash/HEAD_leather_armor_hat.png", "JS_Male/png/slash/HEAD_plate_armor_helmet.png", "JS_Male/png/slash/HEAD_robe_hood.png"], ["JS_Male/png/slash/LEGS_pants_greenish.png", "JS_Male/png/slash/LEGS_plate_armor_pants.png", "JS_Male/png/slash/LEGS_robe_skirt.png"], ["JS_Male/png/slash/WEAPON_dagger.png", "JS_Male/png/slash/WEAPON_dagger.png", "fantasy/weapons/blue_staff.png", "fantasy/weapons/green_staff.png", "fantasy/weapons/red_staff.png", "fantasy/weapons/regular_staff.png", "fantasy/weapons/sword_sheet_128.png", "fantasy/weapons/teal_staff.png", "fantasy/weapons/white_staff.png", "fantasy/weapons/yellow_staff.png"]]

  cast:
   [["JS_Male/png/spellcast/BEHIND_quiver.png"], ["JS_Male/png/spellcast/BODY_male.png", "JS_Male/png/spellcast/BODY_skeleton.png"], ["JS_Male/png/spellcast/BELT_leather.png", "JS_Male/png/spellcast/BELT_rope.png"], ["JS_Male/png/spellcast/FEET_plate_armor_shoes.png", "JS_Male/png/spellcast/FEET_shoes_brown.png"], ["JS_Male/png/spellcast/HANDS_plate_armor_gloves.png"], ["JS_Male/png/spellcast/HEAD_chain_armor_helmet.png", "JS_Male/png/spellcast/HEAD_chain_armor_hood.png", "JS_Male/png/spellcast/HEAD_hair_blonde.png", "JS_Male/png/spellcast/HEAD_leather_armor_hat.png", "JS_Male/png/spellcast/HEAD_plate_armor_helmet.png", "JS_Male/png/spellcast/HEAD_robe_hood.png", "JS_Male/png/spellcast/HEAD_skeleton_eye_glow.png"], ["JS_Male/png/spellcast/LEGS_pants_greenish.png", "JS_Male/png/spellcast/LEGS_plate_armor_pants.png", "JS_Male/png/spellcast/LEGS_robe_skirt.png"], ["JS_Male/png/spellcast/TORSO_chain_armor_jacket_purple.png", "JS_Male/png/spellcast/TORSO_chain_armor_torso.png", "JS_Male/png/spellcast/TORSO_leather_armor_bracers.png", "JS_Male/png/spellcast/TORSO_leather_armor_shirt_white.png", "JS_Male/png/spellcast/TORSO_leather_armor_shoulders.png", "JS_Male/png/spellcast/TORSO_leather_armor_torso.png", "JS_Male/png/spellcast/TORSO_plate_armor_arms_shoulders.png", "JS_Male/png/spellcast/TORSO_plate_armor_torso.png", "JS_Male/png/spellcast/TORSO_robe_shirt_brown.png"]] 

  thrust:
    [["JS_Male/png/thrust/BEHIND_quiver.png"], ["JS_Male/png/thrust/BODY_male.png"], ["JS_Male/png/thrust/TORSO_chain_armor_jacket_purple.png", "JS_Male/png/thrust/TORSO_chain_armor_torso.png", "JS_Male/png/thrust/TORSO_leather_armor_bracers.png", "JS_Male/png/thrust/TORSO_leather_armor_shirt_white.png", "JS_Male/png/thrust/TORSO_leather_armor_shoulders.png", "JS_Male/png/thrust/TORSO_leather_armor_torso.png", "JS_Male/png/thrust/TORSO_plate_armor_arms_shoulders.png", "JS_Male/png/thrust/TORSO_plate_armor_torso.png", "JS_Male/png/thrust/TORSO_robe_shirt_brown.png"], ["JS_Male/png/thrust/BELT_leather.png", "JS_Male/png/thrust/BELT_rope.png"], ["JS_Male/png/thrust/FEET_plate_armor_shoes.png", "JS_Male/png/thrust/FEET_shoes_brown.png"], ["JS_Male/png/thrust/HANDS_plate_armor_gloves.png"], ["JS_Male/png/thrust/HEAD_chain_armor_helmet.png", "JS_Male/png/thrust/HEAD_chain_armor_hood.png", "JS_Male/png/thrust/HEAD_hair_blonde.png", "JS_Male/png/thrust/HEAD_leather_armor_hat.png", "JS_Male/png/thrust/HEAD_plate_armor_helmet.png", "JS_Male/png/thrust/HEAD_robe_hood.png"], ["JS_Male/png/thrust/LEGS_pants_greenish.png", "JS_Male/png/thrust/LEGS_plate_armor_pants.png", "JS_Male/png/thrust/LEGS_robe_skirt.png"], ["JS_Male/png/thrust/WEAPON_shield_cutout_body.png", "JS_Male/png/thrust/WEAPON_shield_cutout_chain_armor_helmet.png", "JS_Male/png/thrust/WEAPON_spear.png", "JS_Male/png/thrust/WEAPON_staff.png"]]

  walkcycle:
    [["JS_Male/png/walkcycle/BEHIND_quiver.png"], ["JS_Male/png/walkcycle/BODY_male.png", "JS_Male/png/walkcycle/BODY_skeleton.png"], ["JS_Male/png/walkcycle/TORSO_chain_armor_jacket_purple.png", "JS_Male/png/walkcycle/TORSO_chain_armor_torso.png", "JS_Male/png/walkcycle/TORSO_leather_armor_bracers.png", "JS_Male/png/walkcycle/TORSO_leather_armor_shirt_white.png", "JS_Male/png/walkcycle/TORSO_leather_armor_shoulders.png", "JS_Male/png/walkcycle/TORSO_leather_armor_torso.png", "JS_Male/png/walkcycle/TORSO_plate_armor_arms_shoulders.png", "JS_Male/png/walkcycle/TORSO_plate_armor_torso.png", "JS_Male/png/walkcycle/TORSO_robe_shirt_brown.png"], ["JS_Male/png/walkcycle/BELT_leather.png", "JS_Male/png/walkcycle/BELT_rope.png"], ["JS_Male/png/walkcycle/FEET_plate_armor_shoes.png", "JS_Male/png/walkcycle/FEET_shoes_brown.png"], ["JS_Male/png/walkcycle/HANDS_plate_armor_gloves.png"], ["JS_Male/png/walkcycle/HEAD_chain_armor_helmet.png", "JS_Male/png/walkcycle/HEAD_chain_armor_hood.png", "JS_Male/png/walkcycle/HEAD_hair_blonde.png", "JS_Male/png/walkcycle/HEAD_leather_armor_hat.png", "JS_Male/png/walkcycle/HEAD_plate_armor_helmet.png", "JS_Male/png/walkcycle/HEAD_robe_hood.png"], ["JS_Male/png/walkcycle/LEGS_pants_greenish.png", "JS_Male/png/walkcycle/LEGS_plate_armor_pants.png", "JS_Male/png/walkcycle/LEGS_robe_skirt.png"], ["JS_Male/png/walkcycle/WEAPON_shield_cutout_body.png", "JS_Male/png/walkcycle/WEAPON_shield_cutout_chain_armor_helmet.png"]]


  #copy of walk cycle except for this line

  idle:
    [["JS_Male/png/walkcycle/BEHIND_quiver.png"], ["JS_Male/png/walkcycle/BODY_male.png", "JS_Male/png/walkcycle/BODY_skeleton.png"], ["JS_Male/png/walkcycle/TORSO_chain_armor_jacket_purple.png", "JS_Male/png/walkcycle/TORSO_chain_armor_torso.png", "JS_Male/png/walkcycle/TORSO_leather_armor_bracers.png", "JS_Male/png/walkcycle/TORSO_leather_armor_shirt_white.png", "JS_Male/png/walkcycle/TORSO_leather_armor_shoulders.png", "JS_Male/png/walkcycle/TORSO_leather_armor_torso.png", "JS_Male/png/walkcycle/TORSO_plate_armor_arms_shoulders.png", "JS_Male/png/walkcycle/TORSO_plate_armor_torso.png", "JS_Male/png/walkcycle/TORSO_robe_shirt_brown.png"], ["JS_Male/png/walkcycle/BELT_leather.png", "JS_Male/png/walkcycle/BELT_rope.png"], ["JS_Male/png/walkcycle/FEET_plate_armor_shoes.png", "JS_Male/png/walkcycle/FEET_shoes_brown.png"], ["JS_Male/png/walkcycle/HANDS_plate_armor_gloves.png"], ["JS_Male/png/walkcycle/HEAD_chain_armor_helmet.png", "JS_Male/png/walkcycle/HEAD_chain_armor_hood.png", "JS_Male/png/walkcycle/HEAD_hair_blonde.png", "JS_Male/png/walkcycle/HEAD_leather_armor_hat.png", "JS_Male/png/walkcycle/HEAD_plate_armor_helmet.png", "JS_Male/png/walkcycle/HEAD_robe_hood.png"], ["JS_Male/png/walkcycle/LEGS_pants_greenish.png", "JS_Male/png/walkcycle/LEGS_plate_armor_pants.png", "JS_Male/png/walkcycle/LEGS_robe_skirt.png"], ["JS_Male/png/walkcycle/WEAPON_shield_cutout_body.png", "JS_Male/png/walkcycle/WEAPON_shield_cutout_chain_armor_helmet.png"]]
